spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Agricultural_Forum?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    mail:
      host: smtp.gmail.com
      port: 587
      username: truyenramos420@gmail.com
      password: pgbgixaczrpobbrc

      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true # Giúp SQL dễ đọc hơn
        use_sql_comments: true # Thêm comment vào query Hibernate
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # Ghi lại giá trị tham số khi Hibernate chạy query

logging:
  level:
    org.hibernate.SQL: DEBUG # Ghi lại SQL Hibernate chạy
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Log giá trị tham số của query

jwt:
  secretKey: YourSuperSecretKeyHereMustBeAtLeast32CharactersLong
  expiration: 3600

api:
  prefix: api/v1

cloudinary:
  cloud-name: dey5xwdud
  api-key: 817519282872467
  api-secret: X5teIyL-lyHbr2kfXX2ezQkknBo
  secure: true

# Cấu hình OpenWeather API
openweather:
  api-key: 44343ee37d40a01a662d7c5d7bfdb418
  api-url: https://api.openweathermap.org/data/2.5

# Cấu hình VNPAY
vnpay:
  tmn-code: T4A9FEAR
  hash-secret: 98344NMN3SQ9PXJECUJEZG6EMSM8X1F9
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${app.backend-url}/api/v1/payment/vnpay-return
  ipn-url: ${app.backend-url}/api/v1/payment/vnpay-ipn
  version: 2.1.0
  command: pay
  currency-code: VND
  locale: vn

app:
  frontend-url: http://localhost:3000
  backend-url: https://9f83-42-112-56-163.ngrok-free.app
  payment:
    method: VNPAY # Phương thức thanh toán mặc định

# Cấu hình Momo
momo:
  partnerCode: MOMOBKUN20180529
  partnerName: Agricultural Shop
  accessKey: klm05TvNBzhg7h7j
  secretKey: at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
  apiEndpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirectUrl: https://9f83-42-112-56-163.ngrok-free.app/api/v1/payment/momo/return
  ipnUrl: https://9f83-42-112-56-163.ngrok-free.app/api/v1/payment/momo/ipn
  storeId: Agricultural1
  lang: vi



